import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  bn: {
    // App
    'app.name': 'ডিজিটাল বন্ধু',
    'app.tagline': 'আপনার ব্যবসা ব্যবস্থাপনা সহজ করুন',
    
    // Navigation
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.products': 'পণ্য',
    'nav.inventory': 'ইনভেন্টরি',
    'nav.suppliers': 'সরবরাহকারী',
    'nav.purchases': 'ক্রয়',
    'nav.customers': 'গ্রাহক',
    'nav.pos': 'বিক্রয় (POS)',
    'nav.sales': 'বিক্রয়',
    'nav.salesList': 'বিক্রয় তালিকা',
    'nav.invoices': 'চালান',
    'nav.warranty': 'ওয়ারেন্টি',
    'nav.reports': 'রিপোর্ট',
    'nav.settings': 'সেটিংস',
    'nav.admin': 'এডমিন প্যানেল',
    
    // Inventory
    'inventory.stockLedger': 'স্টক লেজার',
    'inventory.stockIn': 'স্টক ইন',
    'inventory.stockOut': 'স্টক আউট',
    'inventory.adjustment': 'সমন্বয়',
    'inventory.lowStockAlerts': 'কম স্টক সতর্কতা',
    
    // Reports
    'reports.dailySales': 'দৈনিক বিক্রয়',
    'reports.monthlySales': 'মাসিক বিক্রয়',
    'reports.profit': 'লাভ-ক্ষতি',
    'reports.stock': 'স্টক রিপোর্ট',
    'reports.topSelling': 'সর্বাধিক বিক্রিত',
    'reports.customerReport': 'গ্রাহক রিপোর্ট',
    'reports.supplierDue': 'সরবরাহকারী বাকি',
    
    // Dashboard
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.welcome': 'স্বাগতম',
    'dashboard.todayStats': 'আজকের হিসেব',
    'dashboard.sales': 'বিক্রয়',
    'dashboard.purchasesShort': 'ক্রয়',
    'dashboard.due': 'বাকি',
    'dashboard.profit': 'লাভ',
    'dashboard.expenses': 'খরচ',
    'dashboard.todaySales': 'আজকের বিক্রয়',
    'dashboard.todayPurchases': 'আজকের ক্রয়',
    'dashboard.todayDue': 'আজকের বাকি',
    'dashboard.todayProfit': 'আজকের লাভ',
    'dashboard.todayExpenses': 'আজকের খরচ',
    'dashboard.totalProducts': 'মোট পণ্য',
    'dashboard.lowStock': 'কম স্টক',
    'dashboard.totalCustomers': 'মোট গ্রাহক',
    'dashboard.totalDue': 'মোট বাকি',
    'dashboard.recentSales': 'সাম্প্রতিক বিক্রয়',
    'dashboard.quickActions': 'দ্রুত এন্ট্রি',
    'dashboard.totalCash': 'ক্যাশ আছে',
    'dashboard.cashOnHand': 'হাতে নগদ',
    'dashboard.totalStockValue': 'স্টক মূল্য',
    'dashboard.allProductsValue': 'সব পণ্যের মূল্য',
    'dashboard.totalReceivables': 'বাকি পাওনা',
    'dashboard.customerDues': 'গ্রাহকদের বকেয়া',
    'dashboard.totalCapital': 'মূলধন',
    'dashboard.combined': 'সব মিলিয়ে',
    'dashboard.invoices': 'ইনভয়েস',
    'dashboard.purchases': 'পার্চেজ',
    'dashboard.salesDue': 'বিক্রয় বাকি',
    'dashboard.netProfit': 'নেট প্রফিট',
    'dashboard.totalExpense': 'মোট ব্যয়',
    'dashboard.alerts': 'সতর্কতা',
    'dashboard.warrantyExpiring': 'ওয়ারেন্টি শেষ',
    'dashboard.noSalesToday': 'আজ কোন বিক্রয় হয়নি',
    'dashboard.newSale': 'নতুন বিক্রয় করুন',
    'dashboard.allStockOk': 'সব পণ্যের স্টক পর্যাপ্ত',
    'dashboard.pieces': 'পিস',
    'dashboard.viewAll': 'সব দেখুন',
    'dashboard.refresh': 'রিফ্রেশ',
    
    // Quick Actions
    'quickAction.newSale': 'নতুন বিক্রয়',
    'quickAction.newPurchase': 'নতুন ক্রয়',
    'quickAction.quickStock': 'দ্রুত স্টক',
    'quickAction.customers': 'গ্রাহক',
    'quickAction.sale': 'বিক্রয়',
    'quickAction.purchase': 'ক্রয়',
    'quickAction.stock': 'স্টক',
    'quickAction.customer': 'গ্রাহক',
    
    // Products
    'products.title': 'পণ্য তালিকা',
    'products.description': 'আপনার সব পণ্য এখানে দেখুন এবং পরিচালনা করুন',
    'products.addProduct': 'নতুন পণ্য',
    'products.name': 'পণ্যের নাম',
    'products.sku': 'SKU',
    'products.barcode': 'বারকোড',
    'products.category': 'ক্যাটাগরি',
    'products.brand': 'ব্র্যান্ড',
    'products.purchaseCost': 'ক্রয় মূল্য',
    'products.salePrice': 'বিক্রয় মূল্য',
    'products.stock': 'স্টক',
    'products.currentStock': 'বর্তমান স্টক',
    'products.unit': 'একক',
    'products.warranty': 'ওয়ারেন্টি',
    'products.totalProducts': 'মোট পণ্য',
    'products.lowStock': 'কম স্টক',
    'products.outOfStock': 'স্টক শেষ',
    'products.stockValue': 'স্টক মূল্য',
    'products.searchPlaceholder': 'পণ্যের নাম, SKU বা বারকোড দিয়ে খুঁজুন...',
    'products.categoryBrand': 'ক্যাটাগরি/ব্র্যান্ড',
    'products.allCategories': 'সব ক্যাটাগরি',
    'products.allStock': 'সব স্টক',
    'products.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'products.barcodeScanned': 'বারকোড স্ক্যান হয়েছে',
    'products.deleted': 'মুছে ফেলা হয়েছে',
    'products.updated': 'পণ্য আপডেট হয়েছে',
    'products.added': 'নতুন পণ্য যোগ হয়েছে',
    'products.warrantyNone': 'নেই',
    'products.days': 'দিন',
    'products.months': 'মাস',
    'products.years': 'বছর',
    
    // POS / Sales
    'pos.title': 'বিক্রয় (POS)',
    'pos.searchPlaceholder': 'পণ্যের নাম, SKU বা বারকোড দিয়ে খুঁজুন...',
    'pos.scanBarcode': 'বারকোড স্ক্যান করুন',
    'pos.cart': 'কার্ট',
    'pos.items': 'আইটেম',
    'pos.emptyCart': 'কার্ট খালি',
    'pos.selectCustomer': 'গ্রাহক নির্বাচন করুন',
    'pos.subtotal': 'সাবটোটাল',
    'pos.discount': 'ডিসকাউন্ট',
    'pos.grandTotal': 'সর্বমোট',
    'pos.paymentMethod': 'পেমেন্ট মেথড',
    'pos.paidAmount': 'পরিশোধ',
    'pos.dueAmount': 'বাকি',
    'pos.notes': 'নোট',
    'pos.notesOptional': 'নোট (ঐচ্ছিক)',
    'pos.checkout': 'বিক্রয় সম্পন্ন করুন',
    'pos.insufficientStock': 'স্টক অপর্যাপ্ত',
    'pos.onlyXInStock': 'মাত্র {count} পিস স্টক আছে',
    'pos.saleSuccess': 'বিক্রয় সফল!',
    'pos.invoiceNo': 'চালান নং',
    'pos.addedToBalance': 'ব্যালেন্সে যোগ হয়েছে',
    'pos.productAdded': 'যোগ হয়েছে',
    'pos.productNotFound': 'পণ্য পাওয়া যায়নি',
    'pos.cash': 'নগদ',
    'pos.bkash': 'বিকাশ',
    'pos.nagad': 'নগদ',
    'pos.bank': 'ব্যাংক',
    'pos.due': 'বাকি',
    
    // Sales List
    'sales.title': 'বিক্রয় তালিকা',
    'sales.description': 'সব বিক্রয় এবং চালান দেখুন',
    'sales.todaySales': 'আজকের বিক্রয়',
    'sales.monthlySales': 'এই মাসের বিক্রয়',
    'sales.totalDue': 'মোট বাকি',
    'sales.totalInvoices': 'মোট চালান',
    'sales.invoices': 'টি চালান',
    'sales.searchPlaceholder': 'চালান নং, গ্রাহক বা ফোন দিয়ে খুঁজুন...',
    'sales.allStatus': 'সব স্ট্যাটাস',
    'sales.paid': 'পরিশোধিত',
    'sales.partial': 'আংশিক',
    'sales.walkIn': 'ওয়াক-ইন',
    'sales.payDue': 'বাকি পরিশোধ',
    'sales.print': 'প্রিন্ট',
    'sales.printing': 'প্রিন্ট হচ্ছে',
    'sales.noSales': 'কোনো বিক্রয় পাওয়া যায়নি',
    'sales.duePaymentSuccess': 'বাকি পরিশোধ সফল হয়েছে!',
    'sales.invoiceDeleted': 'মুছে ফেলা হয়েছে',
    
    // Invoices
    'invoices.invoiceNo': 'চালান নং',
    'invoices.date': 'তারিখ',
    'invoices.customer': 'গ্রাহক',
    'invoices.total': 'মোট',
    
    // Settings
    'settings.title': 'সেটিংস',
    'settings.store': 'স্টোর',
    'settings.subscription': 'সাবস্ক্রিপশন',
    'settings.invoice': 'চালান',
    'settings.warranty': 'ওয়ারেন্টি',
    'settings.notifications': 'নোটিফিকেশন',
    'settings.users': 'ব্যবহারকারী',
    'settings.language': 'ভাষা',
    'settings.theme': 'থিম',
    'settings.darkMode': 'ডার্ক মোড',
    'settings.lightMode': 'লাইট মোড',
    'settings.system': 'সিস্টেম',
    'settings.appearance': 'এপিয়ারেন্স',
    'settings.languageAndTheme': 'ভাষা ও থিম',
    
    // Common
    'common.save': 'সংরক্ষণ',
    'common.cancel': 'বাতিল',
    'common.delete': 'মুছুন',
    'common.edit': 'সম্পাদনা',
    'common.view': 'দেখুন',
    'common.search': 'সার্চ...',
    'common.filter': 'ফিল্টার',
    'common.add': 'যোগ করুন',
    'common.addNew': 'নতুন যোগ করুন',
    'common.actions': 'কাজ',
    'common.status': 'স্ট্যাটাস',
    'common.date': 'তারিখ',
    'common.total': 'মোট',
    'common.amount': 'পরিমাণ',
    'common.paid': 'পরিশোধিত',
    'common.due': 'বাকি',
    'common.yes': 'হ্যাঁ',
    'common.no': 'না',
    'common.all': 'সব',
    'common.loading': 'লোড হচ্ছে...',
    'common.noData': 'কোন ডাটা নেই',
    'common.success': 'সফল',
    'common.error': 'ত্রুটি',
    'common.bengali': 'বাংলা',
    'common.english': 'English',
    'common.goToDashboard': 'ড্যাশবোর্ডে যান',
    'common.notifications': 'বিজ্ঞপ্তি',
    'common.clickHere': 'ক্লিক করুন',
    
    // Roles
    'roles.owner': 'মালিক',
    'roles.manager': 'ম্যানেজার',
    'roles.staff': 'স্টাফ',
    
    // Customers
    'customers.title': 'গ্রাহক',
    'customers.description': 'গ্রাহক তালিকা পরিচালনা করুন',
    'customers.totalCustomers': 'মোট গ্রাহক',
    'customers.totalDue': 'মোট বাকি',
    'customers.withDue': 'বাকিধারী',
    
    // Suppliers
    'suppliers.title': 'সরবরাহকারী',
    'suppliers.description': 'সরবরাহকারী তালিকা পরিচালনা করুন',
    
    // Purchases
    'purchases.title': 'ক্রয়',
    'purchases.description': 'সব ক্রয় দেখুন এবং পরিচালনা করুন',
    
    // Home Page
    'home.login': 'লগইন',
    'home.freeTrial': 'ফ্রি ট্রায়াল',
    'home.topSoftware': 'বাংলাদেশের #১ ইনভেন্টরি সফটওয়্যার',
    'home.heroTitle1': 'আপনার ব্যবসার হিসাব',
    'home.heroTitle2': 'একদম স্মার্ট করুন',
    'home.heroDescription': 'স্টক, বিক্রয়, ক্রয়, কাস্টমার ও রিপোর্ট—সবকিছু এক জায়গায়। বাংলায় সহজ UI, দ্রুত POS, আর প্রিমিয়াম এক্সপেরিয়েন্স।',
    'home.startFreeTrial': 'ফ্রি ট্রায়াল শুরু করুন',
    'home.viewFeatures': 'সুবিধা দেখুন',
    'home.benefit1': '৩ দিন ফ্রি ট্রায়াল',
    'home.benefit2': 'সেটআপ ছাড়াই শুরু করুন',
    'home.benefit3': 'ব্যবসা বাড়ান সহজে',
    'home.benefit4': 'অটোমেটিক ইনভয়েস',
    'home.liveDashboard': 'লাইভ ড্যাশবোর্ড',
    'home.quickAction': 'দ্রুত অ্যাকশন',
    'home.sync': 'সিঙ্ক: অন',
    'home.live': 'লাইভ',
    'home.featuresTitle': 'সুযোগ-সুবিধা',
    'home.featuresDescription': 'আপনার ব্যবসা পরিচালনার জন্য প্রয়োজনীয় সব টুলস এক জায়গায়',
    'home.feature1Title': 'স্টক ম্যানেজমেন্ট',
    'home.feature1Desc': 'রিয়েল-টাইম স্টক ট্র্যাকিং, লো স্টক অ্যালার্ট এবং অটোমেটিক স্টক আপডেট।',
    'home.feature2Title': 'ওয়ারেন্টি ট্র্যাকিং',
    'home.feature2Desc': 'প্রোডাক্ট ওয়ারেন্টি ম্যানেজমেন্ট এবং QR কোড জেনারেশন।',
    'home.feature3Title': 'POS সিস্টেম',
    'home.feature3Desc': 'দ্রুত বিক্রয়, বারকোড স্ক্যানিং এবং মাল্টিপল পেমেন্ট মেথড সাপোর্ট।',
    'home.feature4Title': 'কাস্টমার ম্যানেজমেন্ট',
    'home.feature4Desc': 'কাস্টমার প্রোফাইল, বাকি হিসাব এবং ক্রয় ইতিহাস ট্র্যাকিং।',
    'home.feature5Title': 'রিপোর্ট ও অ্যানালিটিক্স',
    'home.feature5Desc': 'বিক্রয়, লাভ-ক্ষতি এবং ব্যবসার সম্পূর্ণ বিশ্লেষণ।',
    'home.feature6Title': 'মোবাইল ফ্রেন্ডলি',
    'home.feature6Desc': 'যেকোনো ডিভাইসে কাজ করুন - ফোন, ট্যাবলেট বা কম্পিউটার।',
    'home.howItWorksTitle': 'কিভাবে কাজ করে?',
    'home.howItWorksDesc': 'মাত্র ৪টি সহজ ধাপে আপনার ব্যবসা ডিজিটাল করুন',
    'home.step1Title': 'রেজিস্ট্রেশন করুন',
    'home.step1Desc': 'ফোন নম্বর দিয়ে ফ্রি অ্যাকাউন্ট তৈরি করুন। কোনো ক্রেডিট কার্ড লাগবে না।',
    'home.step2Title': 'স্টোর সেটআপ করুন',
    'home.step2Desc': 'আপনার দোকানের নাম ও তথ্য দিন। প্রোডাক্ট ও ক্যাটাগরি যোগ করুন।',
    'home.step3Title': 'বিক্রয় শুরু করুন',
    'home.step3Desc': 'POS থেকে বিক্রয় করুন, ইনভয়েস তৈরি করুন এবং স্টক অটো আপডেট হবে।',
    'home.step4Title': 'ব্যবসা বাড়ান',
    'home.step4Desc': 'রিপোর্ট দেখুন, লাভ-ক্ষতি বিশ্লেষণ করুন এবং সিদ্ধান্ত নিন।',
    'home.startNow': 'এখনই শুরু করুন',
    'home.appDemo': 'অ্যাপ ডেমো',
    'home.seePremiumFeatures': 'আমাদের প্রিমিয়াম ফিচার দেখুন',
    'home.demoDescription': 'ড্যাশবোর্ড থেকে শুরু করে POS, রিপোর্ট - সব কিছু এক নজরে',
    'home.todaysAccount': 'আজকের হিসেব 📊',
    'home.pricingTitle': 'সাবস্ক্রিপশন প্যাকেজ',
    'home.pricingDescription': 'আপনার প্রয়োজন অনুযায়ী প্যাকেজ বেছে নিন। সব প্যাকেজে ৩ দিন ফ্রি ট্রায়াল!',
    'home.popular': 'জনপ্রিয়',
    'home.getStarted': 'শুরু করুন',
    'home.paymentMethods': 'পেমেন্ট মেথড: bKash, Nagad, Rocket',
    'home.monthly': 'মাসিক',
    'home.threeMonths': '৩ মাস',
    'home.sixMonths': '৬ মাস',
    'home.oneYear': '১ বছর',
    'home.month': '১ মাস',
    'home.allFeatures': 'সব ফিচার অ্যাক্সেস',
    'home.threeDevices': '৩টি ডিভাইস',
    'home.freeSupport': 'ফ্রি সাপোর্ট',
    'home.dataBackup': 'ডেটা ব্যাকআপ',
    'home.prioritySupport': 'প্রায়োরিটি সাপোর্ট',
    'home.vipSupport': 'VIP সাপোর্ট',
    'home.freeUpgrade': 'ফ্রি আপগ্রেড',
    'home.save14': '১৪% সাশ্রয়',
    'home.save18': '১৮% সাশ্রয়',
    'home.save40': '৪০% সাশ্রয়',
    'home.faqTitle': 'সাধারণ জিজ্ঞাসা',
    'home.faqDescription': 'আমাদের সার্ভিস সম্পর্কে সচরাচর জিজ্ঞাসিত প্রশ্ন ও উত্তর',
    'home.faq1Q': 'ডিজিটাল বন্ধু কী ধরনের ব্যবসার জন্য উপযোগী?',
    'home.faq1A': 'ডিজিটাল বন্ধু সব ধরনের খুচরা দোকান, পাইকারি ব্যবসা, ইলেকট্রনিক্স শপ, মোবাইল শপ, হার্ডওয়্যার স্টোর, ফার্মেসি এবং অন্যান্য ছোট-মাঝারি ব্যবসার জন্য উপযোগী। যেকোনো ব্যবসা যেখানে স্টক, বিক্রয় এবং কাস্টমার হিসাব রাখতে হয়।',
    'home.faq2Q': 'ফ্রি ট্রায়াল কিভাবে কাজ করে?',
    'home.faq2A': 'আপনি সাইন আপ করার পর ৩ দিন ফ্রি ট্রায়াল পাবেন। এই সময়ে আপনি সব ফিচার ব্যবহার করতে পারবেন। ট্রায়াল শেষে আপনার পছন্দমতো প্যাকেজ কিনতে পারবেন। কোনো ক্রেডিট কার্ড লাগবে না।',
    'home.faq3Q': 'পেমেন্ট কিভাবে করব?',
    'home.faq3A': 'আপনি bKash, Nagad বা Rocket এর মাধ্যমে পেমেন্ট করতে পারবেন। পেমেন্ট করার পর ট্রানজেকশন আইডি জমা দিন, আমরা ভেরিফাই করে আপনার সাবস্ক্রিপশন একটিভ করে দেব।',
    'home.faq4Q': 'একটি অ্যাকাউন্টে কতগুলো ডিভাইসে ব্যবহার করা যাবে?',
    'home.faq4A': 'সব প্যাকেজে আপনি ৩টি ডিভাইসে একসাথে ব্যবহার করতে পারবেন। অর্থাৎ আপনি একই অ্যাকাউন্ট দিয়ে ফোন, ট্যাবলেট এবং কম্পিউটারে লগইন করতে পারবেন।',
    'home.faq5Q': 'আমার ডেটা কি নিরাপদ?',
    'home.faq5A': 'হ্যাঁ, আপনার সব ডেটা এনক্রিপ্টেড এবং সুরক্ষিত ক্লাউড সার্ভারে সংরক্ষিত। আমরা নিয়মিত ব্যাকআপ রাখি এবং আপনার ডেটার নিরাপত্তা নিশ্চিত করি। শুধুমাত্র আপনি আপনার ডেটা দেখতে পারবেন।',
    'home.faq6Q': 'ইন্টারনেট ছাড়া কি কাজ করবে?',
    'home.faq6A': 'ডিজিটাল বন্ধু অনলাইন ভিত্তিক সফটওয়্যার, তাই ইন্টারনেট সংযোগ প্রয়োজন। তবে খুব কম ইন্টারনেট স্পিডেও এটি ভালোভাবে কাজ করে। মোবাইল ডেটা দিয়েও ব্যবহার করা যায়।',
    'home.faq7Q': 'সাপোর্ট কিভাবে পাব?',
    'home.faq7A': 'আমাদের ফোন নম্বর 01712-022987 এ কল করতে পারেন বা WhatsApp এ মেসেজ দিতে পারেন। এছাড়াও অ্যাপের ভেতরে সাপোর্ট চ্যাট অপশন আছে। আমরা সকাল ৯টা থেকে রাত ১০টা পর্যন্ত সাপোর্ট দিই।',
    'home.faq8Q': 'সাবস্ক্রিপশন বাতিল করলে ডেটা কি হারিয়ে যাবে?',
    'home.faq8A': 'না, সাবস্ক্রিপশন শেষ হলেও আপনার ডেটা ৩০ দিন পর্যন্ত সংরক্ষিত থাকবে। এই সময়ের মধ্যে রিনিউ করলে সব ডেটা আগের মতোই পাবেন। শুধু নতুন এন্ট্রি করতে পারবেন না।',
    'home.contactTitle': 'যোগাযোগ করুন',
    'home.contactDescription': 'যেকোনো প্রশ্ন বা সাহায্যের জন্য আমাদের সাথে যোগাযোগ করুন',
    'home.phone': 'ফোন',
    'home.email': 'ইমেইল',
    'home.address': 'ঠিকানা',
    'home.addressValue': 'ঢাকা, বাংলাদেশ',
    'home.footerDescription': 'বাংলাদেশের সেরা ইনভেন্টরি ম্যানেজমেন্ট সফটওয়্যার। আপনার ব্যবসার সম্পূর্ণ হিসাব রাখুন সহজে।',
    'home.quickLinks': 'দ্রুত লিংক',
    'home.features': 'সুবিধাসমূহ',
    'home.packages': 'প্যাকেজ',
    'home.faq': 'জিজ্ঞাসা',
    'home.contact': 'যোগাযোগ',
    'home.legal': 'আইনি',
    'home.terms': 'শর্তাবলী',
    'home.privacy': 'গোপনীয়তা নীতি',
    'home.refund': 'রিফান্ড পলিসি',
    'home.copyright': '২০২৪ ডিজিটাল বন্ধু। সর্বস্বত্ব সংরক্ষিত।',
    'home.madeWithLove': 'বাংলাদেশ থেকে ❤️ দিয়ে তৈরি',
    'home.posSystem': 'POS সিস্টেম - দ্রুত বিক্রয়',
    'home.barcodeSearch': 'বারকোড স্ক্যান বা সার্চ করুন...',
    'home.xItems': 'টি আইটেম',
    'home.reports': 'রিপোর্ট',
    'home.monthlyReport': 'মাসিক রিপোর্ট - জানুয়ারি ২০২৪',
    'home.totalSales': 'মোট বিক্রয়',
    'home.totalPurchase': 'মোট ক্রয়',
    'home.grossProfit': 'মোট লাভ',
    'home.profitMargin': 'লাভের হার',
    'home.invoiceCount': 'ইনভয়েস',
    'home.averageSale': 'গড় বিক্রয়',
    'home.paymentSummary': 'পেমেন্ট সামারি',

    // PWA Download
    'pwa.downloadTitle': 'অ্যাপ ডাউনলোড করুন',
    'pwa.downloadSubtitle': 'আপনার মোবাইলে বা ডেস্কটপে অ্যাপ ইনস্টল করুন',
    'pwa.iosTitle': 'iPhone/iPad',
    'pwa.iosStep1': 'Safari ব্রাউজারে এই ওয়েবসাইট ওপেন করুন',
    'pwa.iosStep2': 'নিচের Share বাটনে ক্লিক করুন',
    'pwa.iosStep3': '"Add to Home Screen" অপশনে ক্লিক করুন',
    'pwa.androidTitle': 'Android',
    'pwa.androidStep1': 'Chrome ব্রাউজারে এই ওয়েবসাইট ওপেন করুন',
    'pwa.androidStep2': 'উপরের ⋮ মেনুতে ক্লিক করুন',
    'pwa.androidStep3': '"Install App" বা "Add to Home Screen" ক্লিক করুন',
    'pwa.desktopTitle': 'Desktop',
    'pwa.desktopStep1': 'Chrome/Edge ব্রাউজারে এই ওয়েবসাইট ওপেন করুন',
    'pwa.desktopStep2': 'Address bar এ Install আইকনে ক্লিক করুন',
    'pwa.desktopStep3': '"Install" বাটনে ক্লিক করুন',
    'pwa.installButton': 'এখনই ইনস্টল করুন',
    'pwa.copyLink': 'লিংক কপি করুন',
    'pwa.linkCopied': 'লিংক কপি হয়েছে!',
    'pwa.alreadyInstalled': 'অ্যাপ ইনস্টল করা আছে',
    'pwa.installInstructions': 'ব্রাউজার মেনু থেকে ম্যানুয়ালি ইনস্টল করুন',
  },
  en: {
    // App
    'app.name': 'Digital Bondhu',
    'app.tagline': 'Simplify your business management',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.inventory': 'Inventory',
    'nav.suppliers': 'Suppliers',
    'nav.purchases': 'Purchases',
    'nav.customers': 'Customers',
    'nav.pos': 'POS',
    'nav.sales': 'Sales',
    'nav.salesList': 'Sales List',
    'nav.invoices': 'Invoices',
    'nav.warranty': 'Warranty',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin Panel',
    
    // Inventory
    'inventory.stockLedger': 'Stock Ledger',
    'inventory.stockIn': 'Stock In',
    'inventory.stockOut': 'Stock Out',
    'inventory.adjustment': 'Adjustment',
    'inventory.lowStockAlerts': 'Low Stock Alerts',
    
    // Reports
    'reports.dailySales': 'Daily Sales',
    'reports.monthlySales': 'Monthly Sales',
    'reports.profit': 'Profit & Loss',
    'reports.stock': 'Stock Report',
    'reports.topSelling': 'Top Selling',
    'reports.customerReport': 'Customer Report',
    'reports.supplierDue': 'Supplier Due',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.todayStats': "Today's Stats",
    'dashboard.sales': 'Sales',
    'dashboard.purchasesShort': 'Purchases',
    'dashboard.due': 'Due',
    'dashboard.profit': 'Profit',
    'dashboard.expenses': 'Expenses',
    'dashboard.todaySales': "Today's Sales",
    'dashboard.todayPurchases': "Today's Purchases",
    'dashboard.todayDue': "Today's Due",
    'dashboard.todayProfit': "Today's Profit",
    'dashboard.todayExpenses': "Today's Expenses",
    'dashboard.totalProducts': 'Total Products',
    'dashboard.lowStock': 'Low Stock',
    'dashboard.totalCustomers': 'Total Customers',
    'dashboard.totalDue': 'Total Due',
    'dashboard.recentSales': 'Recent Sales',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.totalCash': 'Total Cash',
    'dashboard.cashOnHand': 'Cash on hand',
    'dashboard.totalStockValue': 'Total Stock Value',
    'dashboard.allProductsValue': 'All products value',
    'dashboard.totalReceivables': 'Total Receivables',
    'dashboard.customerDues': 'Customer dues',
    'dashboard.totalCapital': 'Total Capital',
    'dashboard.combined': 'Combined',
    'dashboard.invoices': 'invoices',
    'dashboard.purchases': 'purchases',
    'dashboard.salesDue': 'Sales due',
    'dashboard.netProfit': 'Net profit',
    'dashboard.totalExpense': 'Total expense',
    'dashboard.alerts': 'Alerts',
    'dashboard.warrantyExpiring': 'Warranty Expiring',
    'dashboard.noSalesToday': 'No sales today',
    'dashboard.newSale': 'Make new sale',
    'dashboard.allStockOk': 'All products have adequate stock',
    'dashboard.pieces': 'pcs',
    'dashboard.viewAll': 'View all',
    'dashboard.refresh': 'Refresh',
    
    // Quick Actions
    'quickAction.newSale': 'New Sale',
    'quickAction.newPurchase': 'New Purchase',
    'quickAction.quickStock': 'Quick Stock',
    'quickAction.customers': 'Customers',
    'quickAction.sale': 'Sale',
    'quickAction.purchase': 'Purchase',
    'quickAction.stock': 'Stock',
    'quickAction.customer': 'Customer',
    
    // Products
    'products.title': 'Products',
    'products.description': 'View and manage all your products here',
    'products.addProduct': 'Add Product',
    'products.name': 'Product Name',
    'products.sku': 'SKU',
    'products.barcode': 'Barcode',
    'products.category': 'Category',
    'products.brand': 'Brand',
    'products.purchaseCost': 'Purchase Cost',
    'products.salePrice': 'Sale Price',
    'products.stock': 'Stock',
    'products.currentStock': 'Current Stock',
    'products.unit': 'Unit',
    'products.warranty': 'Warranty',
    'products.totalProducts': 'Total Products',
    'products.lowStock': 'Low Stock',
    'products.outOfStock': 'Out of Stock',
    'products.stockValue': 'Stock Value',
    'products.searchPlaceholder': 'Search by name, SKU or barcode...',
    'products.categoryBrand': 'Category/Brand',
    'products.allCategories': 'All Categories',
    'products.allStock': 'All Stock',
    'products.noProducts': 'No products found',
    'products.barcodeScanned': 'Barcode scanned',
    'products.deleted': 'deleted',
    'products.updated': 'Product updated',
    'products.added': 'New product added',
    'products.warrantyNone': 'None',
    'products.days': 'days',
    'products.months': 'months',
    'products.years': 'years',
    
    // POS / Sales
    'pos.title': 'Point of Sale',
    'pos.searchPlaceholder': 'Search by name, SKU or barcode...',
    'pos.scanBarcode': 'Scan barcode',
    'pos.cart': 'Cart',
    'pos.items': 'items',
    'pos.emptyCart': 'Cart is empty',
    'pos.selectCustomer': 'Select Customer',
    'pos.subtotal': 'Subtotal',
    'pos.discount': 'Discount',
    'pos.grandTotal': 'Grand Total',
    'pos.paymentMethod': 'Payment Method',
    'pos.paidAmount': 'Paid Amount',
    'pos.dueAmount': 'Due Amount',
    'pos.notes': 'Notes',
    'pos.notesOptional': 'Notes (optional)',
    'pos.checkout': 'Complete Sale',
    'pos.insufficientStock': 'Insufficient Stock',
    'pos.onlyXInStock': 'Only {count} in stock',
    'pos.saleSuccess': 'Sale successful!',
    'pos.invoiceNo': 'Invoice No',
    'pos.addedToBalance': 'added to balance',
    'pos.productAdded': 'added',
    'pos.productNotFound': 'Product not found',
    'pos.cash': 'Cash',
    'pos.bkash': 'bKash',
    'pos.nagad': 'Nagad',
    'pos.bank': 'Bank',
    'pos.due': 'Due',
    
    // Sales List
    'sales.title': 'Sales List',
    'sales.description': 'View all sales and invoices',
    'sales.todaySales': "Today's Sales",
    'sales.monthlySales': "This Month's Sales",
    'sales.totalDue': 'Total Due',
    'sales.totalInvoices': 'Total Invoices',
    'sales.invoices': 'invoices',
    'sales.searchPlaceholder': 'Search by invoice, customer or phone...',
    'sales.allStatus': 'All Status',
    'sales.paid': 'Paid',
    'sales.partial': 'Partial',
    'sales.walkIn': 'Walk-in',
    'sales.payDue': 'Pay Due',
    'sales.print': 'Print',
    'sales.printing': 'Printing',
    'sales.noSales': 'No sales found',
    'sales.duePaymentSuccess': 'Due payment successful!',
    'sales.invoiceDeleted': 'deleted',
    
    // Invoices
    'invoices.invoiceNo': 'Invoice No',
    'invoices.date': 'Date',
    'invoices.customer': 'Customer',
    'invoices.total': 'Total',
    
    // Settings
    'settings.title': 'Settings',
    'settings.store': 'Store',
    'settings.subscription': 'Subscription',
    'settings.invoice': 'Invoice',
    'settings.warranty': 'Warranty',
    'settings.notifications': 'Notifications',
    'settings.users': 'Users',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.system': 'System',
    'settings.appearance': 'Appearance',
    'settings.languageAndTheme': 'Language & Theme',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.add': 'Add',
    'common.addNew': 'Add New',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.total': 'Total',
    'common.amount': 'Amount',
    'common.paid': 'Paid',
    'common.due': 'Due',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.loading': 'Loading...',
    'common.noData': 'No data',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.bengali': 'বাংলা',
    'common.english': 'English',
    'common.goToDashboard': 'Go to Dashboard',
    'common.notifications': 'Notifications',
    'common.clickHere': 'Click here',
    
    // Roles
    'roles.owner': 'Owner',
    'roles.manager': 'Manager',
    'roles.staff': 'Staff',
    
    // Customers
    'customers.title': 'Customers',
    'customers.description': 'Manage customer list',
    'customers.totalCustomers': 'Total Customers',
    'customers.totalDue': 'Total Due',
    'customers.withDue': 'With Due',
    
    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.description': 'Manage supplier list',
    
    // Purchases
    'purchases.title': 'Purchases',
    'purchases.description': 'View and manage all purchases',
    
    // Home Page
    'home.login': 'Login',
    'home.freeTrial': 'Free Trial',
    'home.topSoftware': '#1 Inventory Software in Bangladesh',
    'home.heroTitle1': 'Manage Your Business',
    'home.heroTitle2': 'The Smart Way',
    'home.heroDescription': 'Stock, sales, purchases, customers & reports—all in one place. Easy Bengali UI, fast POS, and premium experience.',
    'home.startFreeTrial': 'Start Free Trial',
    'home.viewFeatures': 'View Features',
    'home.benefit1': '3 Days Free Trial',
    'home.benefit2': 'Start Without Setup',
    'home.benefit3': 'Grow Your Business',
    'home.benefit4': 'Auto Invoice',
    'home.liveDashboard': 'Live Dashboard',
    'home.quickAction': 'Quick Actions',
    'home.sync': 'Sync: On',
    'home.live': 'Live',
    'home.featuresTitle': 'Features',
    'home.featuresDescription': 'All the tools you need to manage your business in one place',
    'home.feature1Title': 'Stock Management',
    'home.feature1Desc': 'Real-time stock tracking, low stock alerts, and automatic stock updates.',
    'home.feature2Title': 'Warranty Tracking',
    'home.feature2Desc': 'Product warranty management and QR code generation.',
    'home.feature3Title': 'POS System',
    'home.feature3Desc': 'Fast sales, barcode scanning, and multiple payment method support.',
    'home.feature4Title': 'Customer Management',
    'home.feature4Desc': 'Customer profiles, due tracking, and purchase history.',
    'home.feature5Title': 'Reports & Analytics',
    'home.feature5Desc': 'Sales, profit-loss, and complete business analysis.',
    'home.feature6Title': 'Mobile Friendly',
    'home.feature6Desc': 'Work on any device - phone, tablet, or computer.',
    'home.howItWorksTitle': 'How It Works?',
    'home.howItWorksDesc': 'Digitize your business in just 4 easy steps',
    'home.step1Title': 'Register',
    'home.step1Desc': 'Create a free account with your phone number. No credit card required.',
    'home.step2Title': 'Setup Store',
    'home.step2Desc': 'Enter your store name and info. Add products and categories.',
    'home.step3Title': 'Start Selling',
    'home.step3Desc': 'Sell from POS, create invoices, and stock auto-updates.',
    'home.step4Title': 'Grow Business',
    'home.step4Desc': 'View reports, analyze profit-loss, and make decisions.',
    'home.startNow': 'Start Now',
    'home.appDemo': 'App Demo',
    'home.seePremiumFeatures': 'See Our Premium Features',
    'home.demoDescription': 'From dashboard to POS, reports - everything at a glance',
    'home.todaysAccount': "Today's Account 📊",
    'home.pricingTitle': 'Subscription Packages',
    'home.pricingDescription': 'Choose a package according to your needs. All packages include 3 days free trial!',
    'home.popular': 'Popular',
    'home.getStarted': 'Get Started',
    'home.paymentMethods': 'Payment Methods: bKash, Nagad, Rocket',
    'home.monthly': 'Monthly',
    'home.threeMonths': '3 Months',
    'home.sixMonths': '6 Months',
    'home.oneYear': '1 Year',
    'home.month': '1 Month',
    'home.allFeatures': 'All Features Access',
    'home.threeDevices': '3 Devices',
    'home.freeSupport': 'Free Support',
    'home.dataBackup': 'Data Backup',
    'home.prioritySupport': 'Priority Support',
    'home.vipSupport': 'VIP Support',
    'home.freeUpgrade': 'Free Upgrade',
    'home.save14': 'Save 14%',
    'home.save18': 'Save 18%',
    'home.save40': 'Save 40%',
    'home.faqTitle': 'Frequently Asked Questions',
    'home.faqDescription': 'Common questions and answers about our service',
    'home.faq1Q': 'What type of businesses is Digital Bondhu suitable for?',
    'home.faq1A': 'Digital Bondhu is suitable for all types of retail stores, wholesale businesses, electronics shops, mobile shops, hardware stores, pharmacies, and other small-medium businesses. Any business that needs to track stock, sales, and customer accounts.',
    'home.faq2Q': 'How does the free trial work?',
    'home.faq2A': 'After signing up, you get 3 days free trial. During this time, you can use all features. After the trial ends, you can purchase your preferred package. No credit card required.',
    'home.faq3Q': 'How do I make payment?',
    'home.faq3A': 'You can pay via bKash, Nagad, or Rocket. After payment, submit the transaction ID, and we will verify and activate your subscription.',
    'home.faq4Q': 'How many devices can I use with one account?',
    'home.faq4A': 'All packages allow you to use 3 devices simultaneously. That means you can login with the same account on phone, tablet, and computer.',
    'home.faq5Q': 'Is my data safe?',
    'home.faq5A': 'Yes, all your data is encrypted and stored on secure cloud servers. We maintain regular backups and ensure your data security. Only you can see your data.',
    'home.faq6Q': 'Does it work without internet?',
    'home.faq6A': 'Digital Bondhu is an online software, so internet connection is required. However, it works well even with low internet speed. You can also use mobile data.',
    'home.faq7Q': 'How do I get support?',
    'home.faq7A': 'You can call our phone number 01712-022987 or message on WhatsApp. There is also a support chat option inside the app. We provide support from 9 AM to 10 PM.',
    'home.faq8Q': 'Will I lose my data if I cancel subscription?',
    'home.faq8A': 'No, your data will be preserved for 30 days after subscription ends. If you renew within this time, you will get all data as before. You just cannot make new entries.',
    'home.contactTitle': 'Contact Us',
    'home.contactDescription': 'Contact us for any questions or help',
    'home.phone': 'Phone',
    'home.email': 'Email',
    'home.address': 'Address',
    'home.addressValue': 'Dhaka, Bangladesh',
    'home.footerDescription': "Bangladesh's best inventory management software. Keep complete account of your business easily.",
    'home.quickLinks': 'Quick Links',
    'home.features': 'Features',
    'home.packages': 'Packages',
    'home.faq': 'FAQ',
    'home.contact': 'Contact',
    'home.legal': 'Legal',
    'home.terms': 'Terms',
    'home.privacy': 'Privacy Policy',
    'home.refund': 'Refund Policy',
    'home.copyright': '© 2024 Digital Bondhu. All rights reserved.',
    'home.madeWithLove': 'Made with ❤️ from Bangladesh',
    'home.posSystem': 'POS System - Quick Sales',
    'home.barcodeSearch': 'Scan barcode or search...',
    'home.xItems': ' items',
    'home.reports': 'Reports',
    'home.monthlyReport': 'Monthly Report - January 2024',
    'home.totalSales': 'Total Sales',
    'home.totalPurchase': 'Total Purchase',
    'home.grossProfit': 'Gross Profit',
    'home.profitMargin': 'Profit Margin',
    'home.invoiceCount': 'Invoices',
    'home.averageSale': 'Avg Sale',
    'home.paymentSummary': 'Payment Summary',

    // PWA Download
    'pwa.downloadTitle': 'Download App',
    'pwa.downloadSubtitle': 'Install the app on your mobile or desktop',
    'pwa.iosTitle': 'iPhone/iPad',
    'pwa.iosStep1': 'Open this website in Safari browser',
    'pwa.iosStep2': 'Tap the Share button at the bottom',
    'pwa.iosStep3': 'Tap "Add to Home Screen" option',
    'pwa.androidTitle': 'Android',
    'pwa.androidStep1': 'Open this website in Chrome browser',
    'pwa.androidStep2': 'Tap the ⋮ menu at the top',
    'pwa.androidStep3': 'Tap "Install App" or "Add to Home Screen"',
    'pwa.desktopTitle': 'Desktop',
    'pwa.desktopStep1': 'Open this website in Chrome/Edge browser',
    'pwa.desktopStep2': 'Click the Install icon in the address bar',
    'pwa.desktopStep3': 'Click the "Install" button',
    'pwa.installButton': 'Install Now',
    'pwa.copyLink': 'Copy Link',
    'pwa.linkCopied': 'Link copied!',
    'pwa.alreadyInstalled': 'App is installed',
    'pwa.installInstructions': 'Install manually from browser menu',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'bn';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
